apiVersion: v1
kind: Pod
metadata:
  name: jenkins-kaniko-agent
  labels:
    jenkins-agent: kaniko
spec:
  serviceAccountName: jenkins
  restartPolicy: Never

  containers:

    - name: jnlp
      image: jenkins/inbound-agent:latest
      args:
        - ${computer.jnlpmac}
        - ${computer.name}
      env:
        - name: JENKINS_URL
          value: "http://jenkins:8080/"
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent

    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      command: ["sleep"]
      args: ["infinity"]
      volumeMounts:
        - name: workspace-volume
          mountPath: /workspace
        - name: kaniko-secret
          mountPath: /kaniko/.docker/

  volumes:
    - name: workspace-volume
      emptyDir: {}
    - name: kaniko-secret
      secret:
        secretName: regcred
